### ISSUE TITLE
How to include the DLGPlayer into an already existing project.

### ISSUE THREAD

**Issue by cdrandin** [DeviLeo/DLGPlayer#4]
I added the DLGPlayer into my project hierarchy.

I followed the instructions for [ffmpeg ios build](https://github.com/kewlbear/FFmpeg-iOS-build-script).

I set the header and library paths to the resulting location from the ffmpeg ios build `../include` and `../lib`.

I linked binaries with library getting all the *.a from ffmpeg under `../lib`.

I end up with `/Users/user/Programming/iOS/app/externals/DLGPlayer/codec/DLGPlayerDecoder.m:16:9: 'libavformat/avformat.h' file not found`.

My only guess could be perhaps I didn't properly import the library or link ffmpeg properly.

**Comment by DeviLeo** [comment]
Please check the paths of the ffmpeg include and lib folders whether are the same as the values of your target's "Header Search Paths" and "Library Search Paths".

If the project has the following folder structure:
- iOS/ffmpeg/include
- iOS/ffmpeg/lib
- iOS/app/externals
- iOS/app/project.xcodeproj

You should set the value "../ffmpeg/include" to "Header Search Paths" and "../ffmpeg/lib" to "Library Search Paths" in the **target** build settings.

**Comment by cdrandin** [comment]
The search paths do have those values set.

Here is [hierarchy](https://gyazo.com/9a7394353c23d551be27bff72a1c1193) if it matters.
[linked frameworks/libraries](https://gyazo.com/b09be57fd915049dc73a67a793e89fda)

**Comment by DeviLeo** [comment]
![screen shot 2017-03-10 at 11 43 23](https://cloud.githubusercontent.com/assets/4043644/23781247/f220beaa-0586-11e7-88f6-d69c11c84d9c.png)
Could you provide the values as the above picture shown and the path of ffmpeg folder in finder?

**Comment by cdrandin** [comment]
Path of `ffmpeg` is `/Users/cdrandin/Programming/iOS/rc_ios_app/Externals/ffmpeg`.

[Header Search Path](https://gyazo.com/f01013ebef4af75a7a7d238d74dc2a71)
[Library Search Path](https://gyazo.com/4100fba58a846e2a056de0b23cecfd76)

**Comment by DeviLeo** [comment]
You missed the folder "rc_ios_app".
"Header Search Path" should be "$(PROJECT_DIR)/**rc_ios_app**/Externals/ffmpeg/include".
"Library Search Path" should be "$(PROJECT_DIR)/**rc_ios_app**/Externals/ffmpeg/lib".

**Comment by cdrandin** [comment]
Oh totally didn't notice that. Um, however, I got a different issue now. I am unsure if I imported the DLGPlayer properly. I do `Add files to 'rc_ios_app'` and dump the DLGPlayer under the `rc_ios_app` root directory.

I then end up with

`Undefined symbols for architecture x86_64:
  "_inflate", referenced from:
      _http_read_stream in libavformat.a(http.o)
      _rtmp_open in libavformat.a(rtmpproto.o)
  "_inflateInit_", referenced from:
      _rtmp_open in libavformat.a(rtmpproto.o)
  "_inflateInit2_", referenced from:
      _http_read_header in libavformat.a(http.o)
  "_zlibCompileFlags", referenced from:
      _http_read_header in libavformat.a(http.o)
  "_inflateEnd", referenced from:
      _http_close in libavformat.a(http.o)
      _http_read_header in libavformat.a(http.o)
      _rtmp_open in libavformat.a(rtmpproto.o)
  "_uncompress", referenced from:
      _id3v2_read_internal in libavformat.a(id3v2.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by DeviLeo** [comment]
Please make sure build the ffmpeg libraries for simulator(x86_64) or use the universal (fat) libraries.

**Comment by cdrandin** [comment]
I followed the README instructions from [here](https://github.com/kewlbear/FFmpeg-iOS-build-script).

I ran the following command to build ffmpeg. `./build-ffmpeg.sh armv7 x86_64`

**Comment by DeviLeo** [comment]
Please locate the project file(.xcodeproj).

e.g.
```
/Users/cdrandin/Programming/iOS/rc_ios_app.xcodeproj
/Users/cdrandin/Programming/iOS/rc_ios_app/Externals/ffmpeg
```
then "$(PROJECT_DIR)" is 
```
/Users/cdrandin/Programming/iOS/".
```
"Header Search Path" should be "$(PROJECT_DIR)/rc_ios_app/Externals/ffmpeg/include".
"Library Search Path" should be "$(PROJECT_DIR)/rc_ios_app/Externals/ffmpeg/lib".

**Comment by cdrandin** [comment]
I already have the `search path` as those.

[finder](https://gyazo.com/4cda3f97ff02fbec7c59702a4a354674)

**Comment by DeviLeo** [comment]
```
rc_ios_app/rc_ios_app.xcodeproj
rc_ios_app/Externals/ffmpeg
```

"Header Search Path" should be "$(PROJECT_DIR)/Externals/ffmpeg/include".
"Library Search Path" should be "$(PROJECT_DIR)/Externals/ffmpeg/lib".

**Comment by cdrandin** [comment]
I have been trying to do couple of different things to get it to working and I have set the search path as you suggested and still getting `/Users/cdrandin/Programming/iOS/rc_ios_app/rc_ios_app/Externals/DLGPlayer/codec/DLGPlayerDecoder.m:16:9: 'libavformat/avformat.h' file not found`

**Comment by cdrandin** [comment]
How would you go about adding DLGPlayer given you are starting with a blank workspace?

**Comment by cdrandin** [comment]
Actually, adding `VideoToolbox.framework` to library linker fixed the issue. I may have justed missed adding it when following the ios ffmpeg build.
